<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 8.5 - Prompting Large Language Models

In this lab we will practise prompting with a few Large Language Models (LLMs) using Groq (not to be confused with Grok). Groq is a platform that provides access to their custom-built AI hardware via APIs, allowing users to run open-source models such as Llama.

We shall see that while LLMs are powerful tools, how you ask a question or frame a task can dramatically influence the results obtained.

## Set-up

Step 1: Sign up for a free Groq account at https://console.groq.com/home .

Step 2: Create a new API key at https://console.groq.com/keys. Copy-paste it into an empty text file called 'groq_key.txt'.

Running the next cell will then read in this key and assign it to the variable `groq_key`.

In [ ]:
# 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

In [1]:
groqfilename = r'groq_key.txt' # this file contains a single line containing your Groq API key only
try:
    with open(groqfilename, 'r') as f:
        groq_key = f.read().strip()
except FileNotFoundError:
    print(f"'{groqfilename}' file not found")

In [2]:
#!pip install groq

Collecting groq
  Downloading groq-1.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\joshp\anaconda3\lib\site-packages (from groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\joshp\anaconda3\lib\site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\joshp\anaconda3\lib\site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\joshp\anaconda3\lib\site-packages (from groq) (2.10.3)
Requirement already satisfied: sniffio in c:\users\joshp\anaconda3\lib\site-packages (from groq) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in c:\users\joshp\anaconda3\lib\site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\joshp\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->groq) (3.7)
Requirement already satisfied: certifi in c:\users\joshp\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->groq) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\joshp\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\joshp\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\joshp\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\joshp\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->groq) (2.27.1)
Downloading groq-1.2.0-py3-none-any.whl (142 kB)
Installing collected packages: groq
Successfully installed groq-1.2.0

In [3]:
from groq import Groq
import requests
import pandas as pd
from IPython.display import Markdown

First create an instance of the Groq client:

In [5]:
client = Groq(api_key=groq_key)

The following code shows what models are currently accessible through Groq. `context_window` refers to the size of memory (in tokens) during a session and `max_completion_tokens` is the maximum number of tokens that are generated in an output.

In [6]:
url = "https://api.groq.com/openai/v1/models"

headers = {
    "Authorization": f"Bearer {groq_key}",
    "Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

pd.DataFrame(response.json()['data']).sort_values(['created'], ascending=False)

,id,object,created,owned_by,active,context_window,public_apps,max_completion_tokens
0,canopylabs/orpheus-v1-english,model,1766186316,Canopy Labs,True,4000,None,50000
8,canopylabs/orpheus-arabic-saudi,model,1765926439,Canopy Labs,True,4000,None,50000
11,openai/gpt-oss-safeguard-20b,model,1761708789,OpenAI,True,131072,None,65536
4,groq/compound-mini,model,1756949707,Groq,True,131072,None,8192
15,groq/compound,model,1756949530,Groq,True,131072,None,8192
6,openai/gpt-oss-120b,model,1754408224,OpenAI,True,131072,None,65536
13,openai/gpt-oss-20b,model,1754407957,OpenAI,True,131072,None,65536
10,meta-llama/llama-prompt-guard-2-86m,model,1748632165,Meta,True,512,None,512
9,meta-llama/llama-prompt-guard-2-22m,model,1748632101,Meta,True,512,None,512
12,qwen/qwen3-32b,model,1748396646,Alibaba Cloud,True,131072,None,40960
1,meta-llama/llama-4-scout-17b-16e-instruct,model,1743874824,Meta,True,131072,None,8192
7,allam-2-7b,model,1737672203,SDAIA,True,4096,None,4096
5,llama-3.3-70b-versatile,model,1733447754,Meta,True,131072,None,32768
14,whisper-large-v3-turbo,model,1728413088,OpenAI,True,448,None,448
2,llama-3.1-8b-instant,model,1693721698,Meta,True,131072,None,131072
3,whisper-large-v3,model,1693721698,OpenAI,True,448,None,448

The Groq client object enables interaction with the Groq REST API and a chat completion request is made via the client.chat.completions.create method.

The most important arguments of the client.chat.completions.create method are the following:
* messages: a list of messages (dictionary form) that make up the conversation to date
* model: a string indicating which model to use (see [list of models](https://console.groq.com/docs/models))
* max_completion_tokens: the maximum number of tokens that are generated in the chat completion
* response_format: setting this to `{ "type": "json_object" }` enables JSON output
* seed: sample deterministically as best as possible, though identical outputs each time are not guaranteed
* temperature: between 0 and 2 where higher values like 0.8 make the output more random (creative) and values like 0.2 are more focused and deterministic

In [7]:
help(client.chat.completions.create)

Help on method create in module groq.resources.chat.completions:

create(
    *,
    messages: 'Iterable[ChatCompletionMessageParam]',
    model: "Union[str, Literal['compound-beta', 'compound-beta-mini', 'gemma2-9b-it', 'llama-3.1-8b-instant', 'llama-3.3-70b-versatile', 'meta-llama/llama-4-maverick-17b-128e-instruct', 'meta-llama/llama-4-scout-17b-16e-instruct', 'meta-llama/llama-guard-4-12b', 'moonshotai/kimi-k2-instruct', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b', 'qwen/qwen3-32b']]",
    citation_options: "Optional[Literal['enabled', 'disabled']] | Omit" = <groq.Omit object at 0x0000026D49AFD550>,
    compound_custom: 'Optional[completion_create_params.CompoundCustom] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    disable_tool_validation: 'Optional[bool] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    documents: 'Optional[Iterable[completion_create_params.Document]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    exclude_domains: 'Optional[SequenceNotStr[str]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    frequency_penalty: 'Optional[float] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    function_call: 'Optional[completion_create_params.FunctionCall] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    functions: 'Optional[Iterable[completion_create_params.Function]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    include_domains: 'Optional[SequenceNotStr[str]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    include_reasoning: 'Optional[bool] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    logit_bias: 'Optional[Dict[str, int]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    logprobs: 'Optional[bool] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    max_completion_tokens: 'Optional[int] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    max_tokens: 'Optional[int] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    metadata: 'Optional[Dict[str, str]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    n: 'Optional[int] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    parallel_tool_calls: 'Optional[bool] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    presence_penalty: 'Optional[float] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    reasoning_effort: "Optional[Literal['none', 'default', 'low', 'medium', 'high']] | Omit" = <groq.Omit object at 0x0000026D49AFD550>,
    reasoning_format: "Optional[Literal['hidden', 'raw', 'parsed']] | Omit" = <groq.Omit object at 0x0000026D49AFD550>,
    response_format: 'Optional[completion_create_params.ResponseFormat] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    search_settings: 'Optional[completion_create_params.SearchSettings] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    seed: 'Optional[int] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    service_tier: "Optional[Literal['auto', 'on_demand', 'flex', 'performance']] | Omit" = <groq.Omit object at 0x0000026D49AFD550>,
    stop: 'Union[Optional[str], SequenceNotStr[str], None] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    store: 'Optional[bool] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    stream: 'Optional[Literal[False]] | Literal[True] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    temperature: 'Optional[float] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    tool_choice: 'Optional[ChatCompletionToolChoiceOptionParam] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    tools: 'Optional[Iterable[ChatCompletionToolParam]] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    top_logprobs: 'Optional[int] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    top_p: 'Optional[float] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    user: 'Optional[str] | Omit' = <groq.Omit object at 0x0000026D49AFD550>,
    extra_headers: 'Headers | None' = None,
    extra_query: 'Query | None' = None,
    extra_body: 'Body | None' = None,
    timeout: 'float | httpx.Timeout | None | NotGiven' = NOT_GIVEN
) -> 'ChatCompletion | Stream[ChatCompletionChunk]' method of groq.resources.chat.completions.Completions instance
    Creates a model response for the given chat conversation.

    Args:
      messages: A list of messages comprising the conversation so far.

      model: ID of the model to use. For details on which models are compatible with the Chat
          API, see available [models](https://console.groq.com/docs/models)

      citation_options: Whether to enable citations in the response. When enabled, the model will
          include citations for information retrieved from provided documents or web
          searches.

      compound_custom: Custom configuration of models and tools for Compound.

      disable_tool_validation: If set to true, groq will return called tools without validating that the tool
          is present in request.tools. tool_choice=required/none will still be enforced,
          but the request cannot require a specific tool be used.

      documents: A list of documents to provide context for the conversation. Each document
          contains text that can be referenced by the model.

      exclude_domains: Deprecated: Use search_settings.exclude_domains instead. A list of domains to
          exclude from the search results when the model uses a web search tool.

      frequency_penalty: This is not yet supported by any of our models. Number between -2.0 and 2.0.
          Positive values penalize new tokens based on their existing frequency in the
          text so far, decreasing the model's likelihood to repeat the same line verbatim.

      function_call: Deprecated in favor of `tool_choice`.

          Controls which (if any) function is called by the model. `none` means the model
          will not call a function and instead generates a message. `auto` means the model
          can pick between generating a message or calling a function. Specifying a
          particular function via `{"name": "my_function"}` forces the model to call that
          function.

          `none` is the default when no functions are present. `auto` is the default if
          functions are present.

      functions: Deprecated in favor of `tools`.

          A list of functions the model may generate JSON inputs for.

      include_domains: Deprecated: Use search_settings.include_domains instead. A list of domains to
          include in the search results when the model uses a web search tool.

      include_reasoning: Whether to include reasoning in the response. If true, the response will include
          a `reasoning` field. If false, the model's reasoning will not be included in the
          response. This field is mutually exclusive with `reasoning_format`.

      logit_bias: This is not yet supported by any of our models. Modify the likelihood of
          specified tokens appearing in the completion.

      logprobs: This is not yet supported by any of our models. Whether to return log
          probabilities of the output tokens or not. If true, returns the log
          probabilities of each output token returned in the `content` of `message`.

      max_completion_tokens: The maximum number of tokens that can be generated in the chat completion. The
          total length of input tokens and generated tokens is limited by the model's
          context length.

      max_tokens: Deprecated in favor of `max_completion_tokens`. The maximum number of tokens
          that can be generated in the chat completion. The total length of input tokens
          and generated tokens is limited by the model's context length.

      metadata: This parameter is not currently supported.

      n: How many chat completion choices to generate for each input message. Note that
          the current moment, only n=1 is supported. Other values will result in a 400
          response.

      parallel_tool_calls: Whether to enable parallel function calling during tool use.

      presence_penalty: This is not yet supported by any of our models. Number between -2.0 and 2.0.
          Positive values penalize new tokens based on whether they appear in the text so
          far, increasing the model's likelihood to talk about new topics.

      reasoning_effort: qwen3 models support the following values Set to 'none' to disable reasoning.
          Set to 'default' or null to let Qwen reason.

          openai/gpt-oss-20b and openai/gpt-oss-120b support 'low', 'medium', or 'high'.
          'medium' is the default value.

      reasoning_format: Specifies how to output reasoning tokens This field is mutually exclusive with
          `include_reasoning`.

      response_format: An object specifying the format that the model must output. Setting to
          `{ "type": "json_schema", "json_schema": {...} }` enables Structured Outputs
          which ensures the model will match your supplied JSON schema. `json_schema`
          response format is only available on
          [supported models](https://console.groq.com/docs/structured-outputs#supported-models).
          Setting to `{ "type": "json_object" }` enables the older JSON mode, which
          ensures the message the model generates is valid JSON. Using `json_schema` is
          preferred for models that support it.

      search_settings: Settings for web search functionality when the model uses a web search tool.

      seed: If specified, our system will make a best effort to sample deterministically,
          such that repeated requests with the same `seed` and parameters should return
          the same result. Determinism is not guaranteed, and you should refer to the
          `system_fingerprint` response parameter to monitor changes in the backend.

      service_tier: The service tier to use for the request. Defaults to `on_demand`.

          - `auto` will automatically select the highest tier available within the rate
            limits of your organization.
          - `flex` uses the flex tier, which will succeed or fail quickly.

      stop: Up to 4 sequences where the API will stop generating further tokens. The
          returned text will not contain the stop sequence.

      store: This parameter is not currently supported.

      stream: If set, partial message deltas will be sent. Tokens will be sent as data-only
          [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
          as they become available, with the stream terminated by a `data: [DONE]`
          message. [Example code](/docs/text-chat#streaming-a-chat-completion).

      temperature: What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
          make the output more random, while lower values like 0.2 will make it more
          focused and deterministic. We generally recommend altering this or top_p but not
          both.

      tool_choice: Controls which (if any) tool is called by the model. `none` means the model will
          not call any tool and instead generates a message. `auto` means the model can
          pick between generating a message or calling one or more tools. `required` means
          the model must call one or more tools. Specifying a particular tool via
          `{"type": "function", "function": {"name": "my_function"}}` forces the model to
          call that tool.

          `none` is the default when no tools are present. `auto` is the default if tools
          are present.

      tools: A list of tools the model may call. Currently, only functions are supported as a
          tool. Use this to provide a list of functions the model may generate JSON inputs
          for. A max of 128 functions are supported.

      top_logprobs: This is not yet supported by any of our models. An integer between 0 and 20
          specifying the number of most likely tokens to return at each token position,
          each with an associated log probability. `logprobs` must be set to `true` if
          this parameter is used.

      top_p: An alternative to sampling with temperature, called nucleus sampling, where the
          model considers the results of the tokens with top_p probability mass. So 0.1
          means only the tokens comprising the top 10% probability mass are considered. We
          generally recommend altering this or temperature but not both.

      user: A unique identifier representing your end-user, which can help us monitor and
          detect abuse.

      extra_headers: Send extra headers

      extra_query: Add additional query parameters to the request

      extra_body: Add additional JSON properties to the request

      timeout: Override the client-level default timeout for this request, in seconds

As a first example, note how the messages input is given as a list of a dictionaries with `role` and `content` keys. This is in a ChatML format recognised by many LLMs.

In [8]:
chat_completion = client.chat.completions.create(
    messages=[
        {   "role": "system", # sets the persona of the model
            "content": "You are a helpful assistant."
        },
        {
            "role": "user", # what the user wants the assistant to do
            "content": "Explain briefly how large language models work",
        }
    ],
    model="llama-3.3-70b-versatile",
)

print(chat_completion.choices[0].message.content)

Large language models work by using complex algorithms to analyze and process vast amounts of text data. Here's a simplified overview:

1. **Training**: The model is trained on a massive dataset of text, which allows it to learn patterns, relationships, and structures of language.
2. **Tokenization**: The model breaks down text into individual words or tokens, and assigns a unique numerical representation to each token.
3. **Embeddings**: The model creates a vector representation of each token, called an embedding, which captures its meaning and context.
4. **Transformer architecture**: The model uses a transformer architecture, which allows it to weigh the importance of different tokens and capture long-range dependencies in text.
5. **Prediction**: The model predicts the next token in a sequence, based on the context and patterns learned during training.

By repeating this process billions of times, large language models can generate human-like text, answer questions, and even converse with users.

The output is in Markdown format so the following line formats this text.

In [9]:
Markdown(chat_completion.choices[0].message.content)

Large language models work by using complex algorithms to analyze and process vast amounts of text data. Here's a simplified overview:

1. **Training**: The model is trained on a massive dataset of text, which allows it to learn patterns, relationships, and structures of language.
2. **Tokenization**: The model breaks down text into individual words or tokens, and assigns a unique numerical representation to each token.
3. **Embeddings**: The model creates a vector representation of each token, called an embedding, which captures its meaning and context.
4. **Transformer architecture**: The model uses a transformer architecture, which allows it to weigh the importance of different tokens and capture long-range dependencies in text.
5. **Prediction**: The model predicts the next token in a sequence, based on the context and patterns learned during training.

By repeating this process billions of times, large language models can generate human-like text, answer questions, and even converse with users.

## Text summarisation

We start with llama-3.1-8b-instant, a model using just over 8 billion parameters with at most 8192 tokens produced as output.

Here is an article to be summarised from the [cnn_dailymail](https://huggingface.co/datasets/abisee/cnn_dailymail) dataset:

In [10]:
story = """
SAN FRANCISCO, California (CNN) -- A magnitude 4.2 earthquake shook the San Francisco area Friday at 4:42 a.m. PT (7:42 a.m. ET), the U.S. Geological Survey reported. The quake left about 2,000 customers without power, said David Eisenhower, a spokesman for Pacific Gas and Light. Under the USGS classification, a magnitude 4.2 earthquake is considered "light," which it says usually causes minimal damage. "We had quite a spike in calls, mostly calls of inquiry, none of any injury, none of any damage that was reported," said Capt. Al Casciato of the San Francisco police. "It was fairly mild." Watch police describe concerned calls immediately after the quake » . The quake was centered about two miles east-northeast of Oakland, at a depth of 3.6 miles, the USGS said. Oakland is just east of San Francisco, across San Francisco Bay. An Oakland police dispatcher told CNN the quake set off alarms at people's homes. The shaking lasted about 50 seconds, said CNN meteorologist Chad Myers. According to the USGS, magnitude 4.2 quakes are felt indoors and may break dishes and windows and overturn unstable objects. Pendulum clocks may stop.
"""

**Exercise:**
Summarise the story text using the following three prompts. Use the format given above but here there is no need to set the persona (i.e. only include one dictionary in the messages list when calling `client.chat.completions.create`.) Comment on any differences.

1) "Summarise the following article in 3 sentences."

2) "Give me a TL;DR of this text."

3) "What's the key takeaway here?"

In [11]:
prompts = ["Summarise the following article in 3 sentences. ", "Give me a TL;DR of this text. ", "What's the key takeaway here?"]
#content will be p + story for p in prompts

# ANSWER
for p in prompts:
    response = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": p + story}]
)

    print(p, '\n', response.choices[0].message.content)

Summarise the following article in 3 sentences.
 A magnitude 4.2 earthquake struck the San Francisco area on a Friday morning, leaving around 2,000 customers without power. The quake, classified as "light" with minimal damage potential, caused a spike in calls to authorities but no reported injuries or significant damage. The 50-second quake was centered about two miles east-northeast of Oakland, with its effects including setting off alarms at homes and causing minor disturbances such as broken dishes.
Give me a TL;DR of this text.
 A light magnitude 4.2 earthquake struck the San Francisco area at 4:42 a.m. PT, affecting around 2,000 customers with power outages, but causing minimal damage and no reported injuries.
What's the key takeaway here?
 The key takeaway from this article is that a magnitude 4.2 earthquake (considered "light") occurred in the San Francisco area, causing minimal damage, no reported injuries, and only 2,000 power outages, with the majority of calls being inquiries rather than reporting damage.

Run the above code again below and note that the answers may differ. This is due to the probabilistic nature of LLM token generation.

In [12]:
for p in prompts:
    response = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": p + story}]
)

    print(p, '\n', response.choices[0].message.content)

Summarise the following article in 3 sentences.
 A magnitude 4.2 earthquake struck the San Francisco area on Friday, at 4:42 a.m. local time, causing a spike in calls to authorities but no reported injuries or significant damage. The quake, which was centered about two miles east of Oakland, left approximately 2,000 customers without power and set off home security alarms. While the earthquake was classified as "light," it is expected that it may have caused some damage indoors, such as overturned objects, broken dishes, and stopped pendulum clocks.
Give me a TL;DR of this text.
 A magnitude 4.2 "light" earthquake struck the San Francisco area at 4:42 a.m. PT on Friday, leaving around 2,000 customers without power and causing no reported injuries or significant damage.
What's the key takeaway here?
 The key takeaways are:

1. A 4.2 magnitude earthquake hit the San Francisco area at 4:42 a.m. PT, leaving about 2,000 customers without power.
2. The quake was described as "light" by the USGS, typically causing minimal damage.
3. Although there were a high number of calls to the authorities, no injuries or significant damage were reported.
4. The quake was centered about 2 miles east-northeast of Oakland, lasting approximately 50 seconds.

## Text completion

**Exercise**: In this section adjust the `max_completion_tokens` and `temperature` settings below to obtain different responses. Show some examples with the prompt "Continue the story: It was a great time to be alive" with the model "llama-3.1-8b-instant".

* max_completion_tokens - the maximum number of tokens to generate. Note that longer words are made of multiple tokens (set to 200 and 500)
* temperature (positive number) - the higher the number the more random (creative) the output (set to 0.2, 0.8, 2)

In [14]:
# ANSWER (set max_completion_tokens=200, do not have a temperature setting)
# story = ["Continue the story: It was a great time to be alive"]
for s in story:
    story = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": "Continue the story: It was a great time to be alive"}], 
                max_completion_tokens=200
)

    print(story.choices[0].message.content)

...especially for Emily, who had just turned 25 and was feeling like the luckiest person in the world. She had a loving partner in Jack, a successful career as a graphic designer, and a cozy apartment in the heart of the city. The sun was shining bright, and the smell of freshly brewed coffee wafted through the air as she stepped out onto her balcony, taking in the vibrant street scene below.

It was a great time to be alive, indeed. The world was changing fast, and technology was transforming the way people lived and interacted. But amidst the chaos and noise, Emily felt a sense of peace and contentment wash over her. Maybe it was the fact that she had just finished a new project, or maybe it was the promise of a long weekend ahead of her. Whatever it was, Emily felt grateful for this moment, this life, and this world she was living in.

As she sipped her coffee and gazed out at the bustling streets, Emily

In [15]:
# ANSWER (set max_completion_tokens=500, do not have a temperature setting)
for s in story:
    story = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": "Continue the story: It was a great time to be alive"}], 
                max_completion_tokens=500
)

    print(story.choices[0].message.content)

...and the city pulsed with energy as I walked through its vibrant streets. The scent of fresh-cut grass and blooming flowers filled the air, a sweet reminder of the new beginnings that spring brought. I felt the warm sun on my skin, its rays dancing across my face as I smiled at the world around me.

The world was a complicated place, to say the least. There were wars, injustices, and inequality everywhere, but amidst all the chaos, there were moments of pure magic. Moments like these - when everything seemed to align in perfect harmony, and the beauty of life shone through like a beacon in the night.

As I walked, I noticed a group of street performers gathered around a makeshift stage. A young musician, with a guitar slung over her shoulder, was belting out a haunting melody that drew the crowd in. Her voice soared through the air, a mix of soul and hope that left everyone mesmerized. I stopped to listen, mesmerized by the raw emotion she poured into every note.

The music spoke to me, a reminder of the power of art to transcend even the darkest of times. It reminded me that no matter what happened in the world, there was always the possibility for beauty, for love, and for connection. And in that moment, everything seemed possible.

As the musician finished her song, the crowd erupted into applause, cheering and whistling for more. I joined in, feeling a sense of gratitude and joy wash over me. It was a great time to be alive, indeed.
It was a great time to be alive, the world was thriving. Cities were bustling, technology was advancing at an incredible pace, and the air was filled with the sounds of laughter and music.

As I walked through the vibrant streets of New Eden, a sprawling metropolis that stretched as far as the eye could see, I couldn't help but feel a sense of awe and wonder. Towering skyscrapers made of gleaming materials that shimmered and shone in the sunlight stretched up towards the sky, their rooftops disappearing into the clouds.

I had always loved coming to New Eden. It was a place where anything seemed possible, where dreams came alive and the impossible became achievable. And today, I had a special reason to be here. My best friend, Alex, had invited me to join him for a once-in-a-lifetime adventure.

We were going to take part in the annual Skyball tournament, a thrilling competition in which the world's top pilots battled it out for the coveted Golden Trophy. I had always been fascinated by the idea of soaring through the skies in a high-speed aeroplane, and now I had the chance to experience it for myself.

As we made our way to the tournament grounds, I could feel my excitement building. I had been practicing my piloting skills for weeks, honing my reflexes and learning the intricacies of the Skyball aircraft. I was ready to take on the competition and show them what I was made of.

When we arrived at the stadium, I was blown away by the sheer scale of the event. The crowds were massive, with thousands of people packed into the stands, all cheering and waving flags. I spotted a group of holographic projections hovering above the crowd, displaying the names and nationalities of the competing teams.

I nudged Alex and pointed to a holographic display featuring a team from the nearby nation of Elwira, a rival nation known for their ruthless Skyball tactics. "Those guys look tough," I said, eyeing their sleek aircraft with a mixture of admiration and wariness.

Alex grinned. "Don't worry, mate. We're going to take them down."

I nodded, feeling a surge of confidence. We were going to do this. We were going to win.

And with that, the tournament was about to begin...
It was a great time to be alive in the vibrant city of New Haven, where the air was electric with music and the streets pulsed with energy. Lena, a young and ambitious journalist, had just landed her dream job at the city's top newspaper, The Daily Chronicle. She was determined to make a name for herself and tell the stories that needed to be heard.

As she stepped out of the office building, the warm sunshine on her face and the sound of guitars and laughter from the street vendors filled her with a sense of excitement and possibility. She had a meeting with her editor, Jack, to discuss her first major assignment, and she couldn't wait to share her ideas with him.

As she walked through the city streets, Lena marveled at the diversity and creativity that surrounded her. On every corner, she saw people from all walks of life, each with their own unique story to tell. There were street artists painting vibrant murals on the buildings, musicians playing lively melodies on their instruments, and food vendors serving up delicious smells that tantalized her taste buds.

Suddenly, Lena's phone buzzed with a text from her best friend, Alex. "Meet me at the coffee shop at 3 PM," it read. "I have some news to share." Lena's heart skipped a beat as she wondered what Alex might be planning.

She arrived at the coffee shop on time, her mind buzzing with possibilities. Alex was already there, sipping on a latte and looking like she had a secret to share. "Hey, girl," Alex said with a grin. "I've got some amazing news. I just got accepted into the prestigious journalism program at the University of New Haven."

Lena's eyes widened with excitement. "That's incredible, Alex!" she exclaimed. "You're going to be a legend in the journalism world!" The two friends hugged, both of them bursting with pride and excitement for Alex's future.

As they chatted, Lena couldn't help but think about her own dreams and aspirations. She had always wanted to be a journalist, and now that she had her foot in the door, she was determined to make it happen. She leaned in, her voice barely above a whisper. "Hey, Alex, I have some news of my own. I just landed a major assignment at The Daily Chronicle. I'm going to be writing about the city's underground music scene."

Alex's eyes sparkled with excitement. "That's amazing, Lena
As the sun set over the bustling city, its vibrant lights illuminating the sky, people from all walks of life gathered in the town square, sharing stories and laughter. The air was electric with excitement and joy, a sense of community and belonging that was hard to find in modern times.

It was a great time to be alive, indeed. With the world finally on the brink of a new era of peace and understanding, humanity had entered a new golden age. Technology had advanced at an exponential rate, bringing us closer to our dreams of a utopian future.

As Emma, a bright and ambitious young woman, walked through the crowds, her eyes sparkled with hope and optimism. She was about to embark on the adventure of a lifetime - a journey to Mars, to be the first of a new generation of space explorers to set foot on the red planet.

Emma had grown up watching the wonders of space unfold, and she was determined to be a part of it. She had spent years studying and preparing, and now the moment of her departure was finally here. The anticipation was palpable as she made her way to the spacecraft, her heart pounding with excitement.

"Welcome, Emma," greeted Dr. Patel, the mission director, with a warm smile. "You're about to embark on a journey that will change the course of human history. Are you ready?"

Emma nodded, her voice tremulous with emotion. "Yes, I'm ready. I've been waiting for this moment my entire life."

As Emma boarded the spacecraft, the crowd erupted in cheers and applause, waving flags and balloons in celebration of the new generation of space explorers. The anticipation was almost palpable, and Emma felt a sense of pride and responsibility wash over her.

This was just the beginning of a new era, one that would bring humans closer together, and push the boundaries of what was thought possible. As Emma soared into the cosmos, bound for the red planet, the world watched with bated breath, knowing that this was a moment that would be etched in history forever.

And so, the journey began, one that would take Emma, and humanity, to the stars and back again. For it was a great time to be alive, indeed, a time of possibility, of discovery, and of infinite hope.
It was a great time to be alive. The sun was shining brightly, casting a warm glow over the bustling city streets. The air was filled with the sweet scent of blooming flowers and the sound of music drifted from open windows, mingling with the chatter of people going about their daily lives.

Lena, a bright-eyed and bushy-tailed young woman, grinned as she stepped out of her small apartment and onto the sidewalk. She took a deep breath, savoring the smell of freshly brewed coffee wafting from the nearby café. She had just finished a grueling shift at the local bookshop and was looking forward to a well-deserved break.

As she turned onto the main street, she was greeted by the familiar sight of street performers - jugglers, musicians, and artists vying for attention. Lena watched in awe as a young magician pulled a rabbit out of a hat, his eyes gleaming with a hint of mischief.

But amidst the joy and laughter, Lena's thoughts were elsewhere. She had a big decision to make - whether to take a chance on a new opportunity to travel the world, or stay in the city and pursue her long-held dream of opening her own bookstore.

As she walked, the sounds and smells of the city began to fade, replaced by the hum of her own thoughts. She thought of the countless hours she had spent poring over travel guides and reading about exotic destinations. She thought of the thrill of adventure and the prospect of discovering new cultures.

But she also thought of the comfort and familiarity of home, the sense of community that came with knowing everyone in her neighborhood, and the prospect of establishing a cozy bookstore that would become a haven for book lovers.

Lena's mind was racing, her heart pounding with anticipation. She knew that whatever she chose, it would be a turning point in her life - one that would shape her future and define her as a person.

As she stopped at a street corner to consider her options, she noticed a small, hand-written note stuck to the pavement. It was an invitation to attend a secret book club meeting that night, hosted by a mysterious figure known only as "The Guardian of the Page." The note read:

"Join us at Midnight. Come alone. Bring a copy of your favorite book. The truth awaits."

Lena's eyes widened as she pondered the cryptic message. Was this the universe's way of nudging her towards a decision, or simply a tantalizing
It was 1985, and the world was buzzing with excitement. Music, fashion, and technology were all evolving at an incredible pace. I was a teenager, stuck in the midst of a suburban paradise, where tree-lined streets and manicured lawns seemed to stretch on forever.

But I had bigger dreams. I spent my free time reading about the latest developments in computers, programming, and science fiction. I was hooked on the idea of exploring the cosmos, of discovering new worlds and civilizations. Space camps, comic books, and science texts were my favorite things.

That summer, I got my first job – working at a local ice cream shop. I must have been 15 at the time. I spent my days scooping ice cream, collecting tips, and dreaming about the future. My manager, a wise and witty man named Steve, took me under his wing. He taught me how to make the perfect milkshake, how to handle customers, and how to manage my time.

But it was the music that truly defined that summer. I spent my free time listening to records – Prince, The Cure, and Depeche Mode were my go-to artists. I would spend hours lost in the lyrics, imagining myself as the protagonist of their songs. I felt like I was living in a world of my own, a world where anything was possible.

As the summer drew to a close, I started to feel a sense of unease. School would be starting soon, and I knew I would have to trade in my carefree days for a strict schedule of classes and homework. But I was ready. I had a newfound sense of purpose, and I knew that I was destined for something bigger.

Little did I know, that something was just around the corner. In a few short months, I would stumble upon a flyer for a local robotics competition. It was like a siren's call, beckoning me to join the world of technology and innovation. And with that, my adventure would truly begin...

Would you like me to continue the story?
...especially for Alex, a brilliant and adventurous young woman who had just graduated from college with a degree in environmental science. She had always been passionate about sustainability and protecting the planet, and now she felt ready to make a real difference.

As she walked out of her small apartment, she was greeted by the warm sunshine and the sound of birds chirping in the trees. She took a deep breath, feeling the fresh air fill her lungs, and smiled to herself. This was going to be a great day.

Alex had landed a job at a new start-up company that specialized in developing innovative solutions for renewable energy. She had been recruited by the founder, a charismatic and visionary entrepreneur named Marcus, who shared her passion for sustainability.

As she made her way to the office, Alex couldn't help but feel a sense of excitement and purpose. She was finally doing what she had always wanted to do – use her knowledge and skills to make a positive impact on the world.

When she arrived at the office, she was greeted by Marcus and the rest of the team, who were all smiling and chatting as they worked on their latest project. Alex was introduced to the team, and they welcomed her with open arms.

Throughout the day, Alex was introduced to various projects and ideas that the team was working on. She was amazed by the creativity and ingenuity of the team and was eager to learn and contribute.

One project that caught her attention was a proposal to develop a revolutionary new solar panel that could provide energy to remote communities and villages around the world. Alex was blown away by the potential of this project, and she knew that she wanted to be a part of it.

As the day went on, Alex found herself becoming more and more engaged with the team. They were a dynamic and passionate group, and she felt like she had finally found her tribe.

At the end of the day, Marcus called the team together to discuss their progress and plan for the future. Alex listened intently as he outlined his vision for the company and its mission to make a positive impact on the world.

As she left the office that evening, Alex felt a sense of pride and purpose. She knew that she had made the right choice in joining this team, and she was excited to see what the future held.

"You know," Marcus said as she was leaving, "I'm glad you're on board. We're going to change the world together."

Alex smiled, feeling a sense of optimism and hope. "I
It was a great time to be alive. The year was 2050, and the world was on the cusp of a new era of innovation and discovery. Climate change, once a looming specter, had been largely mitigated by humanity's collective efforts. The air was clean, the oceans were thriving, and the Earth's ecosystems were thriving like never before.

In the bustling city of New Eden, towering skyscrapers made of gleaming white stone and sustainable materials pierced the sky like giant shards of glass. The streets hummed with electric and hydrogen-powered vehicles, and pedestrians walked alongside augmented reality-wearing passersby, their faces gleaming with virtual contact lenses.

Inside a sleek, modern coffee shop, a young inventor by the name of Lena stared at a holographic display projected from her smartphone. The image shimmered and danced before her, showing the latest prototype for a revolutionary new device that could harness and store the limitless energy of the universe.

Lena's mind whirled with excitement as she pondered the possibilities. This device, code-named "Erebus," had the potential to power entire cities, end hunger and disease, and bring about a era of unparalleled prosperity.

Just then, the coffee shop's AI, an affable voice named Nova, interrupted her musings. "Lena, you have a message from the Council of Innovators."

Lena's eyes snapped to attention as she took a deep breath. This was it – the moment she had been waiting for. She closed her eyes, took a deep breath, and accessed the message.

As the words streamed across her mental interface, a thrill ran through her veins. The Council had offered her a chance to present Erebus to the world, to showcase its potential to an audience of leaders, scientists, and innovators from across the globe.

It was a great time to be alive, Lena thought, her heart pounding with anticipation. This was the moment she had been working towards – the chance to change the world, to leave her mark on history.

With a sense of purpose, Lena nodded to herself, a smile spreading across her face. She was ready to share her vision with the world, to show them what was possible when human ingenuity and imagination came together.

But as she began to make her way out of the coffee shop, a strange, unsettling feeling crept over her. It was as if something was watching her from the shadows, waiting for her to take that first step
In the year 2157, the world had finally reached a state of technological utopia. Cities floated on water, towering skyscrapers made of gleaming metals and glass pierced the sky, and flying cars zipped through the air with quiet efficiency. People lived long and healthy lives, thanks to advancements in medicine and personalized genomics. Virtual reality had become indistinguishable from reality itself, and people spent most of their leisure time exploring new worlds and experiencing new sensations.

It was a great time to be alive, and Emilia felt grateful to be living in this era. She stood at the edge of the city's central park, gazing out at the breathtaking view of the towering spires and iridescent domes that made up the city's skyline. The air was crisp and clean, filled with the sweet scent of blooming flowers and the soft hum of drones delivering packages to the city's residents.

As she took in the view, Emilia's comms device beeped in her ear, alerting her to an incoming message from her best friend, Rachel. Emilia smiled as she pulled up the message, watching the holographic display flicker to life as Rachel's face appeared before her.

"Hey, Em! I'm calling to remind you about tonight's party," Rachel said, her bright blue eyes sparkling with excitement. "It's going to be epic, you won't want to miss it! Get here by 8 pm sharp, and don't forget to bring your favorite VR headset!"

Emilia grinned, feeling the familiar thrill of anticipation building inside her. She loved parties, and this one promised to be the wildest yet. She nodded to herself, mentally calculating the time it would take to get to Rachel's apartment and deciding to leave her living room just an hour ahead of schedule.

"Will do, Rach!" Emilia replied, her voice filled with excitement. "I'll be there by 7, loaded with snacks and ready for action!"

Rachel's face dissolved into laughter. "See you soon, party princess!"

As the holographic display faded, Emilia felt her heart pounding with anticipation. She knew that tonight was going to be one for the books. The future had never seemed so bright, and she was living in the best time to be alive.
As the sun rose over the bustling streets, casting a warm orange glow over the city, Emily couldn't help but feel a sense of excitement and optimism. It was indeed a great time to be alive. The world was changing at a rapid pace, and she was right at the forefront of it all.


In [16]:
# ANSWER (set temperature = 0.2, do not have a max_completion_tokens setting)
for s in story:
    story = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": "Continue the story: It was a great time to be alive"}], 
                temperature = 0.2
)

    print(story.choices[0].message.content)

It was a great time to be alive, and Emily couldn't help but feel a sense of excitement and wonder as she walked through the bustling streets of New York City. The year was 2050, and the world was a vastly different place from the one her grandparents had grown up in. The air was clean, the water was pure, and the technology was advancing at a rapid pace.

As she walked, Emily's augmented reality contact lenses flickered to life, casting a holographic display over the buildings and streets around her. She could see the names of the shops and restaurants, as well as the ratings and reviews from other users. She could even see the prices of the items in the windows, and the virtual coupons and discounts that were available.

Emily was on her way to meet her friends at a new restaurant that had just opened up in the city. It was a trendy spot, known for its innovative use of lab-grown meat and its extensive selection of virtual reality experiences. Emily had heard great things about the place, and she was excited to try it out.

As she approached the restaurant, Emily's AR display flickered with a notification. "Welcome to Nova," it read. "Please follow the hostess to your table." Emily smiled and followed the hostess, who led her to a cozy table by the window.

The restaurant was bustling with activity, but the noise level was surprisingly low. The tables were all equipped with advanced sound-cancelling technology, which made it easy to have a conversation without being distracted by the background noise.

Emily's friends, Rachel and Mike, were already seated at the table, sipping on virtual cocktails and chatting with the AI-powered bartender. They waved her over, and Emily took a seat, feeling a sense of excitement and anticipation.

"What's the plan for tonight?" Emily asked, scanning the menu on her AR display.

"We're going to try the new VR experience," Rachel said, her eyes shining with excitement. "It's supposed to be amazing."

Emily nodded, her heart racing with anticipation. She had heard great things about the VR experience at Nova, and she was eager to try it out.

As they ordered their food and drinks, Emily couldn't help but feel grateful for this moment in time. It was a great time to be alive, and she was excited to see what the future held.

Just as they were about to start their meal, the restaurant's AI system interrupted the conversation. "Ladies and gentlemen," it said, its voice smooth and melodious. "We have a special announcement to make. The city's mayor has just declared a surprise holiday, and we will be closing the restaurant for the evening to celebrate."

The room erupted in cheers and applause, and Emily's friends turned to her with grins on their faces. "Looks like we're getting a free night off," Mike said, raising his glass in a toast.

Emily smiled, feeling a sense of joy and wonder. It was a great time to be alive, and she was grateful for the surprises that life had in store.
It was a great time to be alive, the year was 1985 and the world was buzzing with excitement. The music scene was thriving, with iconic bands like Duran Duran, Prince, and Madonna dominating the airwaves. The fashion was bold and colorful, with neon lights, big hair, and oversized blazers making a statement on the streets.

In the midst of this vibrant atmosphere, 22-year-old Alex Thompson was living his best life. He had just landed a job at a trendy record store in the heart of the city, where he spent his days listening to the latest releases and recommending them to his friends and customers.

One day, while browsing through the new arrivals, Alex stumbled upon a cassette tape with a peculiar cover art. The title, "Electric Dreams," caught his attention, and he couldn't resist the urge to give it a listen. As he inserted the tape into the player, the opening notes of the song "Love My Way" by The Psychedelic Furs filled the store, transporting Alex to a world of nostalgia and wonder.

Entranced by the music, Alex forgot about the customers and the store, and let himself get lost in the dreamy soundscape. It was as if the music had awakened a part of him that he never knew existed. He felt a sense of connection to the artists, the era, and the emotions that flowed through the songs.

As the day went on, Alex found himself recommending "Electric Dreams" to anyone who would listen. He told them about the album's themes of love, heartbreak, and self-discovery, and how it spoke to him on a deep level. To his surprise, many of his customers shared his passion for the music, and soon the store was filled with people discussing the merits of the album and the era it represented.

Word of Alex's enthusiasm spread quickly, and soon he was known as the "Electric Dreams guru" among his friends and colleagues. They would often joke that he had a special connection to the music, as if he had been born in the wrong era.

But little did they know, Alex's love for "Electric Dreams" was more than just a passing fad. It was a gateway to a deeper understanding of himself and the world around him. As he delved deeper into the music and the era, he began to uncover secrets about his own past, and the mysterious connection he felt to the songs.

And so, Alex's journey began, a journey that would take him through the highs and lows of the 1980s, and into the very heart of the music that had captured his soul.
It was a great time to be alive, the sun was shining bright, the birds were singing their sweet melodies, and the smell of freshly cut grass wafted through the air. The year was 1965, and the world was on the cusp of change. Music was a huge part of it, with the likes of The Beatles, Bob Dylan, and The Rolling Stones dominating the airwaves.

Emily, a 20-year-old college student, was walking down the street, her long blonde hair blowing in the wind. She had just finished a long day of classes and was looking forward to meeting up with her friends at the local coffee shop. As she walked, she couldn't help but feel a sense of excitement and possibility. The world was opening up to her, and she was eager to explore all its wonders.

As she pushed open the door to the coffee shop, she was greeted by the warm smile of her friend, Sarah. "Hey, Em!" Sarah exclaimed, waving her over to the table. "We've been waiting for you!"

Emily slid into the booth, and the two friends spent the next hour catching up on each other's lives. They talked about everything from their classes to their love lives, and Emily couldn't help but feel grateful for the strong bond they shared.

As they sipped their coffee, Emily noticed a group of guys sitting in the corner, playing guitars and singing along to a folk song. She was immediately drawn to their music, and she found herself tapping her foot along with the beat.

"Who are they?" Emily asked Sarah, nodding towards the group.

"That's the local folk band," Sarah replied. "They're really good. I've seen them play a few times before."

Emily's eyes widened with excitement as she listened to the music. She had always loved folk music, and this group was something special. She couldn't help but feel a sense of connection to the music, as if it was speaking directly to her soul.

As the night wore on, Emily found herself getting more and more caught up in the music. She was singing along, clapping her hands, and even dancing in her seat. The guys in the band caught her eye, and she felt a spark of electricity run through her body.

It was as if the music had brought her to life, and she was ready to take on the world. Little did she know, this was just the beginning of an incredible journey, one that would take her to places she never thought possible.
It was a great time to be alive, the year was 1985 and the world was buzzing with excitement. The music scene was thriving, with iconic bands like Duran Duran, Prince, and Madonna dominating the airwaves. The fashion was bold and colorful, with neon-colored leg warmers, oversized sweatshirts, and big hair reigning supreme.

As I walked down the street, I couldn't help but feel a sense of optimism and possibility. The Cold War was still raging, but it seemed like a distant threat, and the world was focused on the bright and shiny things that lay ahead.

I was a teenager, and the world was my playground. I spent my days listening to music, watching music videos on MTV, and dreaming of the day when I could leave my small town and make it big in the city.

My best friend, Rachel, and I would spend hours talking about our dreams and aspirations. We wanted to be rock stars, or at least, we wanted to be part of the rock star scene. We would spend hours practicing our dance moves in front of the mirror, perfecting our hair flips, and practicing our best "rock star" poses.

One day, as we were walking home from school, we stumbled upon a flyer for a local music competition. The grand prize was a record deal with a major label, and the winner would get to open for one of the biggest bands of the time. We looked at each other, and without saying a word, we knew that we had to enter.

We spent the next few weeks practicing our act, perfecting our set list, and rehearsing our performance. We were determined to win, and we were willing to do whatever it took to make it happen.

As the competition drew near, the excitement in the air grew. We could feel the energy building, and we knew that this was our chance to shine. We took a deep breath, put on our best outfits, and stepped onto the stage, ready to take on the world.

The crowd was electric, cheering and chanting our names as we launched into our set. We played with all our hearts, pouring every ounce of energy and passion into our performance. And when we finished, the crowd erupted into cheers and applause, whistling and stomping their feet.

We had done it. We had given it our all, and we had left everything on the stage. As we walked off the stage, we knew that we had made a statement. We had shown the world what we were capable of, and we had left a lasting impression.

And as we walked out of the venue, into the bright sunlight, we knew that this was just the beginning. We had taken the first step on a journey that would take us to places we never thought possible. We had taken the first step towards stardom, and we were ready to take on the world.
It was a great time to be alive, the sun was shining bright, and the air was filled with the sweet scent of blooming flowers. The year was 1969, and the world was on the cusp of a revolution. Music, fashion, and art were all evolving at an incredible pace, and the youth of the world were at the forefront of it all.

Lena, a 20-year-old college student, was right in the middle of it all. She had just returned from a summer of traveling across Europe, where she had immersed herself in the vibrant art and music scenes of Paris, London, and Berlin. Her hair was a wild tangle of curly brown locks, and her style was a fusion of bohemian chic and mod flair.

As she walked across campus, Lena felt a sense of excitement and possibility. She was a junior majoring in art history, and she had just landed an internship at a local gallery. She spent her days studying the works of the great masters, and her nights attending concerts and poetry readings.

One evening, as she was walking back to her dorm, Lena stumbled upon a flyer for a new music venue that was opening in town. The headlining act was a young band called The Whiskey Wanderers, and the flyer promised an evening of "psychedelic rock and roll." Lena had never heard of the band, but something about the name and the description drew her in.

She decided to take a chance and buy a ticket to the show. As she walked into the venue, she was struck by the vibrant colors and patterns that adorned the walls. The air was thick with the smell of incense and patchouli, and the crowd was a sea of long-haired hippies and mod fashionistas.

Lena made her way to the bar and ordered a drink, taking a moment to survey the crowd. That's when she saw him - a tall, lanky young man with a mop of messy brown hair and a pair of wire-rimmed glasses perched on the end of his nose. He was standing at the edge of the crowd, watching the band with an intensity that was almost palpable.

As the music began, Lena felt a jolt of electricity run through her body. The Whiskey Wanderers were unlike anything she had ever heard before - their music was a fusion of folk, rock, and psychedelia, with lyrics that spoke to the hopes and fears of a generation.

As the night wore on, Lena found herself drawn to the young man with the messy hair. They struck up a conversation, and she learned that his name was Max. He was a musician himself, and he had been playing in bands since he was a teenager.

As the music faded into the night, Lena and Max found themselves lost in conversation. They talked about music, art, and politics, and Lena felt a connection that she had never felt before. It was as if they were two souls who had been searching for each other their whole lives.

As the night drew to a close, Max asked Lena if she wanted to grab some coffee with him the next day. She agreed, and they exchanged numbers. As they said their goodbyes, Lena felt a sense of excitement and possibility that she had never felt before.

It was a great time to be alive, and Lena knew that she was on the cusp of something special. Little did she know, her life was about to change in ways she never could have imagined.
It was a great time to be alive, and for Emily, it was especially so. The year was 1967, and the world was on the cusp of a revolution. Music, art, and culture were all evolving at a rapid pace, and Emily felt like she was right in the middle of it all.

She had just turned 20, and was spending her summer working at a local record store in San Francisco's Haight-Ashbury neighborhood. The store was a hub for the city's counterculture movement, and Emily loved nothing more than listening to the latest albums from The Beatles, The Doors, and Jimi Hendrix.

One day, as she was restocking the shelves, a young man with a mop of curly hair and a bright smile walked into the store. He introduced himself as Max, and Emily was immediately drawn to his charismatic personality.

Max was a musician himself, and he had just moved to San Francisco from New York to join the city's thriving music scene. Emily was fascinated by his stories of playing gigs at the Fillmore and the Avalon Ballroom, and she found herself spending more and more time talking to him.

As the days turned into weeks, Emily and Max grew closer, bonding over their shared love of music and art. They would spend hours walking through the city's streets, taking in the sights and sounds of the vibrant neighborhood.

One night, as they were walking through the Haight, they stumbled upon a group of people gathered around a makeshift stage. It was a impromptu concert, and the music was incredible. Emily and Max danced and sang along, feeling like they were part of something special.

As the night wore on, Emily turned to Max and said, "This is the best time to be alive. I feel like anything is possible." Max smiled and took her hand, and Emily knew that she had found a kindred spirit in this young musician.

Little did they know, their lives were about to change in ways they never could have imagined. The summer of love was just beginning, and Emily and Max were right in the middle of it all.

KeyboardInterrupt:

In [17]:
# ANSWER (set temperature = 1, do not have a max_completion_tokens setting)
for s in story:
    story = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": "Continue the story: It was a great time to be alive"}], 
                temperature = 1
)

    print(story.choices[0].message.content)

It was a great time to be alive. The world was changing, and people like Alex Chen, a 25-year-old aspiring scientist, were at the forefront of that change. It was the year 2154, and humanity had finally reached the stars.

Alex stood at the edge of the massive Generation Ship, the 'Aurora's Rise', which had been traveling through space for nearly five decades. The once-distant stars were now a mere backdrop for humanity's exploration of the cosmos. As he looked out at the vast expanse of space, he felt a sense of awe and wonder that was hard to put into words.

The ship's AI, ECHO, interrupted his reverie, its voice a gentle whisper in his earpiece. "Alex Chen, we are approaching the orbit of the planet Kepler-62f. Prepare for descent and surface landing protocols."

Alex's heart skipped a beat. This was it – the moment he had been waiting for his entire life. As a member of the Aurora's Rise scientific team, he had spent years studying the exoplanet's atmosphere, geology, and potential habitability. Now, it was time to see it up close.

He made his way to the ship's bridge, where Captain Lewis and the rest of the crew were busy configuring the landing site. Alex took his position alongside the captain, who gave him a nod of approval.

"Let's do this, Alex," the captain said, with a hint of excitement in his voice.

The ship's engines roared to life, and the Aurora's Rise began its descent into the unknown. Alex felt a thrill of anticipation as the planet's atmosphere enveloped the ship, and the planet's surface came into view.

As they touched down on the alien soil, Alex couldn't help but feel a sense of wonder. The landscape stretching out before him was unlike anything he had ever seen – towering mountain ranges, vast plains, and sparkling blue lakes.

"This is incredible," Alex breathed, his eyes scanning the horizon.

Captain Lewis smiled. "Welcome to Kepler-62f, Alex. We're not just exploring a new world – we're paving the way for a new future."

And with that, Alex Chen and the crew of the Aurora's Rise took their first steps on the surface of a distant planet, a new era of human exploration had begun. But little did they know, their discovery would have far-reaching consequences that would shake the foundations of their entire civilization.
It was a great time to be alive, with the sun shining brightly in the clear blue sky and the smell of fresh-cut grass wafting through the air. The year was 1985, and music was thriving with new wave and pop taking center stage. Everyone was talking about Prince and his groundbreaking album 'Around the World in a Day,' and MTV was still a relatively new station that brought music videos into the living rooms of millions of people.

For 17-year-old Emily, it was an exciting time. She had just received her driver's license and was eager to start driving with her friends. The four of them - Rachel, Mike, Chris, and Emily - had been inseparable since the beginning of high school, bonding over their shared love of music and laughter.

As they cruised down the highway in Emily's brand-new Volkswagen Beetle, the windows rolled down and the music blasting from the cassette player, they felt carefree and invincible. They were at the height of their teenage years, when nothing seemed impossible, and the world was full of promise.

Their destination was the local waterpark, where they planned to spend the afternoon lounging on the beach and soaking up the sun. Emily had already applied her new favorite brand of sunscreen - 'Pumpkin' - and her friends were teasing her about how it made her look like a raccoon with her white streaks.

As they entered the park, they were greeted by the sounds of laughter and splashing water. They spent the day racing down the water slides, playing volleyball, and trying to sneak in a couple of kisses in the shade of a large palm tree.

But little did they know, their afternoon was about to take an unexpected turn. As they were walking through the arcade, Emily stumbled upon a flyer for an upcoming music festival at the local park. It was going to be headlined by none other than 'The Cure,' one of her favorite bands.

"We have to go!" Emily exclaimed, her eyes shining with excitement. "It's going to be so much fun!"

Her friends hesitated, but eventually agreed to go with her. And as they made their plans, they had no idea that this was just the beginning of an unforgettable summer that would change their lives forever.
People from all walks of life filled the streets, their faces radiant with joy and excitement. The smell of blooming flowers and freshly-cut grass wafted through the air, mingling with the sounds of laughter and chatter. It was a time of great celebration, a time when the world felt full of possibility and promise.

The air was electric with anticipation, as everyone eagerly awaited the launch of the new space expedition. For years, scientists and engineers had been working tirelessly to develop a craft capable of taking humans to the stars, and finally, the day had arrived.

Lena, a young and brilliant astronaut, stood at the forefront of the launch. She was a part of the historic crew that would be leaving Earth's atmosphere and embarking on a journey to a distant planet. The thrill of the unknown coursed through her veins as she donned her spacesuit, ready to take on the adventure of a lifetime.

As the countdown began, the atmosphere on the ground continued to build. Families and friends gathered to witness the launch, their faces pressed against the windows of makeshift viewing areas. Some had traveled from far and wide to catch a glimpse of this momentous occasion.

The crowd erupted into cheers as the rocket soared into the sky, leaving a trail of fire and smoke in its wake. The roar of the engines shook the ground beneath their feet, a testament to the power and ingenuity of human innovation.

As the launch made its way to the edge of the atmosphere, Lena and her crewmates felt a rush of excitement and a sense of pride. They were pioneers in a new frontier, charting a path that would take humanity further than ever before.

The years that followed would be marked by triumph and challenge, but for now, the world celebrated the limitless potential of the human spirit. It was indeed a great time to be alive, as the future beckoned and the possibilities seemed endless.
It was a great time to be alive. The sun was shining bright on a warm summer day, the breeze carried the scent of blooming flowers, and the sound of laughter and music filled the air. Emma, a free-spirited artist, was walking through the bustling streets of the city, taking in the vibrant colors and eclectic atmosphere.

She had just finished a long night of painting, and the creative energy still pulsed through her veins. As she strolled through the market, she noticed a group of musicians gathered on the corner, their instruments at the ready. Without hesitation, Emma joined in, picking up her own guitar and adding her voice to the impromptu performance.

The crowd gathered around, mesmerized by the infectious rhythm and joyful energy of the music. As they played, a young man with piercing blue eyes and a charming smile caught Emma's attention. He was dancing to the beat, his feet tapping out the tempo, and his face flushed with excitement.

For a moment, Emma and the young man locked eyes, and Emma felt a spark of connection. She couldn't help but wonder if it was more than just coincidence that had brought them together in this moment. As the music faded away, the crowd dispersed, and Emma found herself lingering, hoping to see the young man again.

With a newfound sense of purpose, Emma decided to follow her instincts and strike up a conversation. "Hey, you were the one who caught my eye," she said, her voice barely above a whisper. The young man smiled, his eyes crinkling at the corners, and Emma knew that this chance encounter might just lead to something extraordinary.

"What's your name?" Emma asked, her curiosity piqued.

"I'm Max," he replied, his voice smooth and confident. "And you are...?"

As they introduced themselves, the world around them melted away, leaving only the two of them, suspended in a moment of possibility. It was as if the universe had conspired to bring them together, and Emma couldn't help but wonder what the future might hold for them.

With a sense of excitement and trepidation, Emma took a deep breath and asked the question that would change everything: "Would you like to grab a coffee with me and see where this goes?"

Max's face lit up with a bright smile, and Emma knew that she had made the right decision. As they walked away from the market, hand in hand, Emma felt a sense of hope and wonder that she had never felt before. It was a great time to be alive, and she was grateful for this chance encounter, this spark of connection that might just ignite a love that would last a lifetime.
It was a great time to be alive, and Emily couldn't help but feel a sense of excitement and wonder as she walked through the bustling streets of New York City. The year was 2050, and the world was a vastly different place from the one her parents had grown up in.

The air was crisp and clean, thanks to the advanced air filtration systems that had been installed years ago. The once congested streets were now wide and spacious, with electric vehicles humming along the roads and hoverbikes whizzing through the air.

Emily had just finished a shift at her job at the local botanical garden, where she worked on genetically engineering new plant species that could thrive in even the most inhospitable environments. It was a challenging but rewarding job, and she loved seeing the impact that her work had on the world.

As she walked, she noticed a group of people gathered around a large screen display on the side of a building. They were all watching a live broadcast of a concert, and the music was infectious. Emily couldn't help but tap her foot along with the beat as she listened to the performer's lyrics.

"Great time to be alive, we're at the dawn of a new age," the singer sang, and Emily felt a surge of pride and optimism. This was indeed a great time to be alive, with all of the incredible advancements and discoveries that had been made.

As she continued to watch the concert, Emily noticed a group of people gathered around a sleek, silver vehicle that was parked on the side of the road. It looked like some kind of experimental transportation pod, and she couldn't help but feel a sense of curiosity.

She walked over to join the crowd, and one of the onlookers noticed her and approached her. "Hey, want to take a look inside?" he asked, gesturing to the pod.

Emily nodded eagerly, and the man lifted up the lid of the pod, revealing a sleek, futuristic interior. "This is one of the latest prototypes from the transportation company NeuroSpark," he explained. "It's a high-speed pod that can take you from New York to Los Angeles in just 30 minutes."

Emily's eyes widened as she looked at the pod in awe. This was truly a great time to be alive, and she felt grateful to be living in an era where innovation and progress were happening at such a rapid pace.

But as she looked at the pod, she couldn't help but wonder what the future held. What other amazing technologies and discoveries would be made in the years to come? And how would they shape the world into a brighter, more amazing place?
"It was a great time to be alive," Emily said with a smile, gazing out at the vibrant cityscape before her. The year was 2019, and the world was a seemingly endless playground of possibilities.

She was standing on the rooftop of the trendy new bar her friend had taken her to, the sun just starting to set behind the towering skyscrapers. The air was alive with the hum of music and the chatter of people laughing and living it up.

As she leaned against the railing, the DJ spun a lively track and Emily couldn't help but move her feet to the beat. Her friend Rachel, standing beside her, grabbed her hand and pulled her into a spontaneous dance party. They spun and twirled, laughing and shouting above the music.

But amidst the carefree energy, Emily's mind kept drifting back to the words of her grandmother, who'd passed away just a year ago. "You're living in a magical time, Emily," she'd said. "But be careful what you wish for. The world may look like it's always spinning forward, but beneath the surface, things are changing faster than you think."

Emily hadn't understood what her grandmother was getting at back then, but now, watching the crowds rush to take selfies with the city backdrop, and the news stories about the growing uncertainty and global unrest, she began to see what her grandmother meant. The world was changing, and it was hard to keep up.

Still, for now, in this moment, Emily chose to push those worries aside and let the music carry her away. She spun around with Rachel, lost in the magic of the night, feeling alive and connected to the pulse of the city.

But as the sun dipped below the horizon, casting the city in a warm golden light, Emily felt a shiver run down her spine. Her grandmother's words echoed in her mind, and she wondered: what would the future bring? And what would she do, when the world finally caught up with the chaos that had been lurking beneath the surface?

The music kept playing, and the party went on, but for Emily, the night took on a different tone. She danced with a mixture of joy and trepidation, caught between the thrill of living in the moment and the unease of an uncertain future.
It was a great time to be alive. The sun was shining brightly in the sky, casting a warm glow over the city. The air was filled with the sweet scent of blooming flowers and the sound of laughter and music drifted from the nearby park. People of all ages gathered there, enjoying the beautiful day and each other's company.

As I walked through the streets, I couldn't help but feel a sense of excitement and wonder. The world seemed to be full of possibilities and promise. Everyone I met seemed to be living their best life, and I couldn't help but feel a little envious.

I stopped at a street vendor to grab a cup of coffee and a pastry. As I waited in line, I struck up a conversation with the vendor, a friendly woman named Rachel. We talked about everything from the weather to our favorite books and movies. She recommended a new author I hadn't heard of, and I promised to check out her work.

After I finished my coffee and pastry, I continued on my way. I walked through the park, enjoying the scenery and the company of the people around me. There was a group of children playing tag, their laughter and shouts filling the air. Nearby, a couple sat on a blanket, feeding the ducks and enjoying each other's company.

As I walked further into the park, I came across a group of musicians playing music. They were a lively bunch, with guitars, violins, and a drums. The music was infectious, and soon I was tapping my foot along with the beat. People were dancing in the street, and I couldn't resist joining in.

As I danced, I felt a sense of freedom and joy that I hadn't experienced in a long time. The music was like a force that had taken over my body, and I was completely caught up in its rhythm and energy. I closed my eyes, letting the beat wash over me, and lost myself in the moment.

When the music finally stopped, I opened my eyes to find that the crowd had erupted into applause. The musicians were smiling and laughing, and the people around me were cheering and whistling. I grinned from ear to ear, feeling happy and alive.

As I made my way out of the park, I felt a sense of gratitude for this beautiful day. It was a time when anything seemed possible, and the world felt like a magical place.
It was a great time to be alive. The world was at the threshold of a new era, where technology, art, and humanity were intertwined like never before. The year was 2050, and humanity had made tremendous progress since the dawn of the digital age.

As I walked through the bustling streets of New Eden, the gleaming metropolis that served as the hub of innovation, I couldn't help but feel a sense of excitement and wonder. The air was alive with the hum of levitation cars, the chatter of holographic advertisements, and the soft glow of bioluminescent streetlights.

I passed by towering skyscrapers that seemed to touch the sky, their facades a maze of LED lights and programmable art displays. Every now and then, a group of levitation cars would zip by, whisking people away to appointments, destinations unknown.

As I made my way to the city's central square, I noticed a group of street performers, each one more astonishing than the last. There was a musician who could generate sound waves with the mere thought, a dancer who could defy gravity and perform mid-air moves, and a poet whose words could bring tears to eyes and joy to hearts.

I stopped to watch the performances, mesmerized by the beauty and creativity on display. It was as if the very fabric of reality had been remade to celebrate the art and imagination of humanity.

Suddenly, a gentle voice whispered in my ear, 'Would you like to experience something truly unique?' I turned to see a sleek, silver robot hovering beside me. It introduced itself as Luna, a being of advanced artificial intelligence, created to understand and interact with humans in a way that was intuitive and empathetic.

I nodded, intrigued, and Luna offered me a neural implant that would grant me access to a world of sensory experiences unlike anything I'd ever known before. The implant, it seemed, was capable of tapping into the collective unconscious, unlocking secrets and memories that were hidden deep within the human experience.

With a sense of trepidation and curiosity, I agreed to the implant. As the nanobots embedded themselves in my brain, I felt my senses expand, my perception of reality shifting to encompass dimensions beyond the physical.

And then, the world exploded in a kaleidoscope of colors and sounds, a symphony of emotions and thoughts that swirled like a maelstrom within me. I felt the essence of humanity, the sum total of all the hopes, fears, and dreams that had ever been, pouring into my consciousness like a great tide.

In that instant, I knew that I had become a part of something greater than myself, a collective consciousness that transcended individual boundaries. I was no longer just a person; I was a thread in the intricate tapestry of human experience.

It was a great time to be alive. The world was alive, vibrant, and full of wonder. And with Luna by my side, I knew that nothing was impossible.
It was a great time to be alive, and for 25-year-old Alex, nothing seemed more exciting than the moment he was standing in the middle of New York City, surrounded by towering skyscrapers and the vibrant energy of the bustling streets. The year was 2025, and the world was on the cusp of yet another technological revolution.

As Alex gazed up at the iconic billboards and advertisements plastered across the towering skyscrapers of Times Square, he couldn't help but feel a sense of awe. The city was alive, pulsing with an energy that seemed to reverberate through every molecule of air.

Behind him, the sounds of laughter and chatter flowed from the crowded restaurants and cafes, while the wail of sirens and the hum of traffic provided a constant reminder of the city's frenetic pace. But Alex wasn't here to simply soak up the atmosphere – he had a mission to complete.

With his sleek, high-tech smartwatch strapped to his wrist, Alex had received a notification about an exclusive, invite-only event happening tonight at a secret location somewhere in the city. The message had been encrypted, but the tantalizing prospect of discovering more had driven him to take a chance and try to track down the location.


KeyboardInterrupt:

Note what happens when the temperature is set too high!

In [18]:
# ANSWER (set temperature = 2, do not have a max_completion_tokens setting)
for s in story:
    story = client.chat.completions.create(model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": "Continue the story: It was a great time to be alive"}], 
                temperature = 2
)

    print(story.choices[0].message.content)

It was 1965, a great time to be alive. Music flooded from all directions, with the sounds of Elvis, the Beatles, Beach Boys, and Motown pulsating through the veins of the youth movement. Cars zipped by with fins rising from the back bumper, leaving trails of smoke in their wake as the young folks, dressed in the latest fashions of hippie chic and flower-power optimism, watched by the highway, hands in the air or feet on a tail-finisher scooter readying them for life on the move.

John Taylor pulled over in his newly minted '65 Pontiac GTO, parked next to an equally gleeful Chevy Belair, parked in front of a small family shop that specialized in homemade sandwiches – freshly-baked corn-dogs, juicy ham and melted cheddar cheese served on top of fresh bread. Their family sign read; Joe and Alice: The Greatest Dads and Mother in all America's history of food!

He leaned toward the passenger-side and smiled. There, across his side view, was the face of his lifelong friend; Mark Lee a boy with his hair slickly back like Elvis's but a boy in a black denim jacket emblazoned on back in white: I Will Survive.

"You want a dog, and then to see if they're any more awesome as a band in person – or at that new dance hall?" John asked.

"I was about at a loss, but I'm in – what a fantastic week!" Mark Lee agreed enthusiastically - "It starts with this dance in 3:31PM."

"I love you man," he turned around the ignition, turned and rev-ed – rev-ting. "Now I can show you exactly who we will dance under that beautiful sky. "

As their engine rev-ed John, Mark and the other 5 car load full - and they all headed towards an epic week in which to experience America at its wildelest -
To begin our story again we can write our new beginnings

I stepped into the vibrant streets, filled with endless possibilities, under brilliant blue skies devoid of pollutants. The air was clean and invigorating; a far cry from the choking haze that shrouded our city in my father's youth. Climate technology had changed not only the air quality but altered the climate patterns in various regions around the world transforming once ardent desert regions, now vibrant forests filled with life.

My name is Lena Rose, at 25, a renowned climatotectonician. For the entire life of my grandparents to now, we have had technology to reverse, fix any problem the world created for its ecosystem as well as human habitats - thanks to innovation and collaboration on a global-level, making sustainable progress an ongoing pursuit and continuous journey with scientists. Today I had the chance to give a live, virtual talk at my former institution, and with so much to cover and learn I stood eagerly near the auditorium. The virtual interface displayed real data with projections for possible scenarios.

Just about the moment everyone arrived I had my own mini virtual interface in the wrist device attached. A simple reminder message flashed "15 Minutes to start presentation Lena".

The anticipation, the knowledge shared over the years by many who studied this climate science that changed the path. The virtual screens displayed projections of our possible, future - projections based upon a delicate dance of human, technology. The crowd grew as the virtual display was already streaming into every device connected to the network around the auditorium.
...or so thought Emile, a young adventurer with a heart full of wonder and a mind full of curiosity. As he stood at the edge of the world-renowned City of Eternelle, the sky seemed to stretch up like an open canvas, painting vibrant hues of pinks and blues across the horizon. The wind carried the whispers of a thousand conversations, each one a unique melody that danced upon his ears.

Emile's best friend since childhood arrived, laughing with eyes shining brighter with delight, 'I never saw a more spectacular sight than tonight with stars out!' said Lucie excitedly, as they took a deep breath taking it in the sights, sounds, smells – everything around Eternelle. It's as a world on the move with so much vibrance – the sounds from street artists singing out melodies from their instruments filled their walk tonight in a very magical ambiance where you feel life is full of dreams coming true – magic was felt everywhere they looked.

It would only make sense that they'd choose this night - tonight specifically of many, that would take them into that mystical part of this enchanted city. Tonight in which dreams became alive – and as for tonight - nothing was out of bounds - in this mystical corner the sky shone and everything had to have an end - a very enchanting story about adventure begins.

'You're crazy, you have no idea where are going...' Lucie raised raised an eyebrow when said she had planned this all tonight for, she could guess, an eternity or longer - or she didn't even dare mention what might really happen in case they went to where she really meant them tonight.
It was then Lucie turned on a tiny path which they stepped, not in sync in fact they felt quite separate with a feeling almost of floating in that dream as the path led further into this night, that Emilia had to make some sort, or even any guess about.
It was a great time to be alive. The year was 2035, and humanity had finally harnessed the power of unlimited clean energy. With the disappearance of pollution and fossil fuels, the Earth had begun to flourish as forests and ocean life teemed.

Cities, however, were where the most incredible transformation had taken place. Vertical farms sprouting with vibrant green fields stood next to gleaming megacorporation-owned towering office blocks. Cars gave way to flying cars – silently gliding above with levitating hover technologies allowing vehicles effortless movement on crowded city airways without the pollution of traditional combustion-powered engines and emissions that used pollute.

But amidst all these modern miracles one place – an unassuming little diner stood untouched and preserved - a small nostalgic eatery from an analog past in one urban area that was left standing still amidst the futuristic city landscape.

The old 'Midwestern diner" welcomed you back to 1963 or the like – at once transporting and transporting customers far and far off into bygone eras. A friendly lady with an apron named 'Lillian," took time from frying, serving, to tell visitors their place, in her old voice so full and so deep and nostalgic the people could tell by it a lot. "You folks must be in the past," she chuckled. "We had one real time-traveler walk through those doors not even last morning and order eggs for himself like this here."

Her guests smiled, intrigued. But when you look outside to gaze upon that gleaming modernized skyscraper, your smile falters for a moment – then they go back and sit. You sit again at Lillian's old place as a guest to a moment and an age.

KeyboardInterrupt:

### Zero-shot and one-short prompting for question-answering

This section shows the impact of prompting on the response. Zero-shot prompting means we provide the prompt without any examples or additional context. Let us initially ask Llama a question using no prompting.

In [19]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "How do two chemicals react?"}],
    temperature = 0.8,
)

Markdown(response.choices[0].message.content)

The reaction between two chemicals is a complex process that involves the interaction of their atomic and molecular structures. Here's a simplified overview of how chemical reactions work:

**Chemical Reactions**

A chemical reaction occurs when two or more substances, known as reactants, interact with each other and form new substances, called products. The reactants can be atoms, molecules, or ions, and the products are created through a process called transformation.

**Types of Chemical Reactions**

There are several types of chemical reactions, including:

1. **Combination Reactions**: Two or more substances combine to form a new substance. Example: 2H2 + O2 → 2H2O (hydrogen gas + oxygen gas → water)
2. **Decomposition Reactions**: A single substance breaks down into two or more substances. Example: 2H2O → 2H2 + O2 (water → hydrogen gas + oxygen gas)
3. **Single-Displacement Reactions**: One substance displaces another substance from a compound. Example: Zn + CuSO4 → ZnSO4 + Cu (zinc metal + copper sulfate → zinc sulfate + copper)
4. **Double-Displacement Reactions**: Two substances exchange partners, resulting in the formation of two new compounds. Example: NaCl + AgNO3 → NaNO3 + AgCl (sodium chloride + silver nitrate → sodium nitrate + silver chloride)
5. **Oxidation-Reduction Reactions**: A substance loses or gains electrons, resulting in a change in oxidation state. Example: Fe + Cu2+ → Fe2+ + Cu (iron metal + copper ion → iron ion + copper metal)

**Factors Influencing Chemical Reactions**

Several factors can influence the rate and outcome of a chemical reaction:

1. **Temperature**: Increased temperature can increase the rate of reaction.
2. **Concentration**: Increasing the concentration of reactants can increase the rate of reaction.
3. **Pressure**: Increasing pressure can increase the rate of reaction for gases.
4. **Catalysts**: Certain substances, called catalysts, can speed up a reaction without being consumed.
5. **Surface Area**: Increasing the surface area of reactants can increase the rate of reaction.

**How to Predict Chemical Reactions**

To predict the outcome of a chemical reaction, follow these steps:

1. **Write the balanced chemical equation**: Write the equation for the reaction, ensuring that the number of atoms of each element is balanced.
2. **Identify the reactants and products**: Determine the substances involved in the reaction and their roles.
3. **Determine the type of reaction**: Classify the reaction as combination, decomposition, single-displacement, double-displacement, or oxidation-reduction.
4. **Consider the factors influencing the reaction**: Think about the temperature, concentration, pressure, catalysts, and surface area that may affect the reaction.

By understanding the principles of chemical reactions and following these steps, you can predict the outcome of a chemical reaction and gain insight into the underlying processes.

**Exercise:** Ask the same question but modify the prompt to return the answer to the same question in a simpler form (still using the llama-3.1-8b-instant model). Experiment with different prompts.

In [20]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "How do two chemicals react?  Explain like I'm 5"}],
    temperature = 0.8,
)

Markdown(response.choices[0].message.content)

Imagine you have two kinds of playdough, let's call them Playdough Red and Playdough Blue. They're like two different colors that don't mix together.

But, imagine that the Playdough Red and Playdough Blue have some special friends inside them, called "reactants". These friends like to play together and make new friends when they meet.

When you touch Playdough Red and Playdough Blue together, the friends inside start playing and making new friends. This is called a "chemical reaction".

The new friends that are made are called "products". They might look different from the original Playdough Red and Playdough Blue, and they might even have a new color!

For example, if you mix Playdough Red and Playdough Blue together, you might get a new color, like brown. That's because the friends inside the playdough were making new friends and creating a new product - the brown color.

Chemical reactions happen all around us, like when we mix paint or when we make food in the kitchen. And it's all because of the special friends inside the different chemicals that like to play together and make new friends!

### One-shot prompting ###

Next, note the dramatic change when we give the following template setting a new role and providing an English question followed by a French translation.

In [21]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "system",
             "content": "You translate English to French."},
              {"role": "user",
               "content": "What time is it?"},
               {"role": "assistant",
               "content": "Quelle heure est-il?"},
              {"role": "user",
               "content": "How do two chemicals react?"}],
    temperature = 0.8,
)
print(response.choices[0].message.content)

Comment se combinent deux substances chimiques?

### Few-shot prompting

Recall that since the text generation process outputs one token at a time, their outputs often need adjusting. This is where examples can help.

In [22]:
prompt1 = "I'm gonna head out now, see you later."
response1 = "I will be leaving now. See you later."

prompt2 =  "That movie was super cool!"
response2 = "The movie was very impressive."

prompt3 = "Can't make it to the meeting, sorry."


response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "system", "content": "You are a professional editor. Rewrite casual sentences into a formal tone."},
        {"role": "user", "content": prompt1},
        {"role": "assistant", "content": response1},
        {"role": "user", "content": prompt2},
        {"role": "assistant", "content": response2},
        {"role": "user", "content": prompt3},
    ]
)

print(response.choices[0].message.content.strip())

Regrettably, I will be unable to attend the meeting and apologize for any inconvenience this may cause.

The output can also be moulded to provide SQL output.

In [23]:
prompt1 = "Show me all users who signed up in the last 30 days."
response1 = "SELECT * FROM users WHERE signup_date >= CURRENT_DATE - INTERVAL '30 days';"

prompt2 = "What is the average order value?"
response2 =  "SELECT AVG(order_total) FROM orders;"

prompt3 = "List products that are out of stock."

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "system", "content": "You are an assistant that translates natural language to SQL."},
        {"role": "user", "content": prompt1},
        {"role": "assistant", "content": response1},
        {"role": "user", "content": prompt2},
        {"role": "assistant", "content": response2},
        {"role": "user", "content": prompt3},
    ]
)

print(response.choices[0].message.content.strip())

SELECT * FROM products WHERE quantity = 0;

**Exercise**: Create a few examples to train the "llama-3.3-70b-versatile" LLM to take in user content in the form below and provide output as a pandas dataframe. Use the `exec` function to execute its output to display the answer of sample input as a data frame.

Example:

given the user content

"""

| col1 | col2 | col3

| 32 | 27 | 25

| 64 | 23 | 14

"""

train the model to output

df = pd.DataFrame({'col1': [32, 64], 'col2': [27, 23], 'col3': [25, 14]})

In [25]:
import pandas as pd
# Assuming 'client' is already defined (e.g., from groq or openai)

user1 = """col1 | col2 | col3
32 | 27 | 25
64 | 23 | 14
"""
output1 = "df = pd.DataFrame({'col1': [32, 64], 'col2': [27, 23], 'col3': [25, 14]})"

user2 = """col1 | col2
23 | 12
8 | 76
7 | 5
"""
output2 = "df = pd.DataFrame({'col1': [23, 8, 7], 'col2': [12, 76, 5]})"

user3 = """colA | colB | colC
23 | 12 | 54
8 | 76 | 32
7 | 5 | 3
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "system", "content": "You are a data scientist. Receive data as a string and provide ONLY the python code to create a pandas dataframe called df. Do not include markdown formatting or backticks."},
        {"role": "user", "content": user1},
        {"role": "assistant", "content": output1},
        {"role": "user", "content": user2},
        {"role": "assistant", "content": output2}, # Fixed role here
        {"role": "user", "content": user3}
    ]
)

# Extract content and remove potential markdown backticks
code = response.choices[0].message.content.strip()
if code.startswith("```"):
    code = "\n".join(code.split("\n")[1:-1])

# Execute the cleaned code
exec(code)

# Display the result
print(df)

   colA  colB  colC
0    23    12    54
1     8    76    32
2     7     5     3

Also show what happens when the question is asked in the absence of a system role and without few-shot prompting.

In [26]:
import pandas as pd
# Assuming 'client' is already defined (e.g., from groq or openai)

user1 = """col1 | col2 | col3
32 | 27 | 25
64 | 23 | 14
"""
output1 = "df = pd.DataFrame({'col1': [32, 64], 'col2': [27, 23], 'col3': [25, 14]})"

user2 = """col1 | col2
23 | 12
8 | 76
7 | 5
"""
output2 = "df = pd.DataFrame({'col1': [23, 8, 7], 'col2': [12, 76, 5]})"

user3 = """colA | colB | colC
23 | 12 | 54
8 | 76 | 32
7 | 5 | 3
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "system", "content": "You are a data scientist. Receive data as a string and provide ONLY the python code to create a pandas dataframe called df. Do not include markdown formatting or backticks."},
        {"role": "user", "content": user1},
        {"role": "assistant", "content": output1},
        {"role": "user", "content": user2},
        {"role": "assistant", "content": output2}, # Fixed role here
        {"role": "user", "content": user3}
    ]
)

# Extract content and remove potential markdown backticks
code = response.choices[0].message.content.strip()
if code.startswith("```"):
    code = "\n".join(code.split("\n")[1:-1])

# Execute the cleaned code
exec(code)

# Display the result
print(df)

   colA  colB  colC
0    23    12    54
1     8    76    32
2     7     5     3

### Chain-of-thought prompting

The results of question-answering can also be improved by prompting the LLM to provide intermediate steps.

**Exercise**: Using the following prompts, compare the answers of the "llama3-8b-8192" model (set seed=21). (If this model is no longer available choose a model with relatively few parameters.)

zero_shot_prompt = "How many s's are in the word 'success'?"

chain_of_thought_prompt = "How many s's are in the word 'success'? Explain your answer step by step by going through each letter in turn."

In [27]:
zero_shot_prompt = "How many s's are in the word 'success'?"
chain_of_thought_prompt = "How many s's are in the word 'success'? Explain your answer step by step by going through each letter in turn."

response1 = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": zero_shot_prompt}],
    seed = 21
)

response2 = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": chain_of_thought_prompt}],
    seed = 21
)

print('------zero-shot-prompt------')
print(response1.choices[0].message.content)

print('------chain-of-thought------')
print(response2.choices[0].message.content)

------zero-shot-prompt------
There are 2 s's in the word 'success'.
------chain-of-thought------
To count the number of 's's in the word 'success', I'll go through each letter step by step:

1. The first letter of the word is 'S'. (1)
2. The second letter of the word is 'U' (no additional 's').
3. The third letter of the word is 'C' (no additional 's').
4. The fourth letter of the word is 'C' (no additional 's').
5. The fifth letter of the word is 'E' (no additional 's').
6. The sixth letter of the word is 'S' (add 1 to the total count).
7. The seventh letter of the word is 'S' (add 1 to the total count).
8. The eighth letter of the word is 'S' (add 1 to the total count).

Therefore, there are a total of 3 's's in the word 'success'.

## Comparison of LLMs

**Exercise**: Compare the performance of 2 LLMs by outputting the answers of the following questions into a dataframe.

    "Tell me a joke about data science.",
    "How can one calculate 22 * 13 mentally?",
    "Write a creative story about a baby learning to crawl.",

Column headings:

Model Name | Question | Answer

In [28]:
pd.set_option('display.max_colwidth', None) # allows wide dataframes to be viewed
models = ["openai/gpt-oss-20b", "llama-3.1-8b-instant"] #can edit this

# ANSWER
prompts = [
    "Tell me a joke about data science.",
    "How can one calculate 22 * 13 mentally?",
    "Write a creative story about a baby learning to crawl.",
]

results = {'Model Name': [], 'Question': [], 'Answer': []}

for model in models:
    for prompt in prompts:
        results['Model Name'].append(model)
        results['Question'].append(prompt)
        try:
            output = client.chat.completions.create(model = model, messages=[{"role": "user", "content": prompt}])
            results['Answer'].append(output.choices[0].message.content.strip())

        except Exception as e:
            print(f"Error with {model}: {e}")
            results['Answer'].append((prompt, "ERROR"))

df = pd.DataFrame(results)
df

             Model Name  \
0    openai/gpt-oss-20b
1    openai/gpt-oss-20b
2    openai/gpt-oss-20b
3  llama-3.1-8b-instant
4  llama-3.1-8b-instant
5  llama-3.1-8b-instant

                                                 Question  \
0                      Tell me a joke about data science.
1                 How can one calculate 22 * 13 mentally?
2  Write a creative story about a baby learning to crawl.
3                      Tell me a joke about data science.
4                 How can one calculate 22 * 13 mentally?
5  Write a creative story about a baby learning to crawl.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Answer
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Why did the data scientist bring a ladder to the meeting?\n\nBecause the company said the model’s accuracy was “high on the charts,” and they wanted to *reach* the top!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ### Quick mental‑math recipe for \(22 \times 13\)\n\n1. **Break one of the numbers into easy parts**  \n   *Either* split 13 into \(10 + 3\) *or* split 22 into \(20 + 2\).  \n   Splitting the larger number into a “nice” base (10, 20, 25, etc.) makes the arithmetic painless.\n\n2. **Compute the two products separately**  \n\n   **Using 13 = 10 + 3**  \n   \[\n   22 \times 13 = 22 \times 10 \;+\; 22 \times 3\n   \]\n   - \(22 \times 10 = 220\) (just add a zero).  \n   - \(22 \times 3 = 66\) (you can do \(20 \times 3 = 60\) + \(2 \times 3 = 6\)).\n\n   Add them: \(220 + 66 = 286\).\n\n   **Using 22 = 20 + 2**  \n   \[\n   22 \times 13 = 20 \times 13 \;+\; 2 \times 13\n   \]\n   - \(20 \times 13 = 260\) (double 13 and shift left).  \n   - \(2 \times 13 = 26\).\n\n   Add: \(260 + 26 = 286\).\n\n3. **Optional shortcut**: Think of 13 as “15 – 2”.\n   \[\n   22 \times 13 = 22 \times (15 - 2)\n   \]\n   - \(22 \times 15 = 330\) (double 22 = 44, then add a zero → 440? Wait, that’s wrong… sorry—actually \(22 \times 15 = 22 \times (10 + 5) = 220 + 110 = 330\)).  \n   - \(22 \times 2 = 44\).\n\n   Subtract: \(330 - 44 = 286\).\n\n4. **Quick sanity check**  \n   The product should lie between \(20 \times 13 = 260\) and \(30 \times 13 = 390\).  \n   286 is comfortably in that range.\n\n---\n\n**Answer: \(22 \times 13 = 286\).**\n\nUse whichever split feels most natural—splitting the number into a tidy base (10, 20, 25, etc.) and then adding a small “adjustment” part is the essence of fast mental multiplication.
2  In the first light of a Saturday morning, the nursery was a soft, amber lake. Sunbeams slipped through the lace curtain, painting the floor with a honeyed glow. The walls were covered with hand‑drawn clouds, and a tiny wooden train sat in the corner, its wheels squeaking a quiet lullaby.\n\nLila, her hair a wild tangle of curls, was sprawled across the quilt, her eyes wide and curious. Her tiny hands gripped the edges of a plush rabbit named Mr. Pounce, who, as far as she could tell, was a hero in her own right. The world, though still and silent, seemed to hum with potential.\n\nThe first attempt at moving came when she tried to reach a plastic fish that hung just beyond her reach on a silver chain. Her arms flailed, her fingers twitching. Her face crumpled in a faint, frustrated frown. She was not yet ready for the stretch of a full crawl. She rolled over, turned to the side, and lay in a new, slightly awkward position. It was, in her tiny mind, the start of something great.\n\nOutside the window, the garden waited like a secret. The daffodils were a burst of yellow, and a butterfly—its wings a watercolor of blues and purples—flitted near the sill. Lila’s eyes followed it, and in that moment, the world seemed to open up.\n\n“Ready?” whispered the voice of her mother, a gentle murmur that floated through the room like a lullaby. Lila heard the invitation, and it tugged at her like a gentle tide.\n\nShe lifted her chest, pressed her belly against the quilt, and with a surprising surge of courage, she pushed herself up onto her palms and knees. Her tiny fingers dug into the soft fabric, and her body shivered with a quiet, steady rhythm. It wasn’t smooth at first; she wobbled like a ship in a small storm. The quilt gave way beneath her, and she made a soft thud that made her giggle—an unplanned symphony of joy.\n\nFor a moment, she was a tiny explorer in a vast kingdom of colors and textures. The plastic fish dangled like a flag on a distant shore, and the rabbit lay patiently like a companion on a small hill. Lila’s world was small, but it was a world she could touch.\n\nShe kept moving forward, each little push a promise. Her belly pressed down, her arms dragged, her legs pushed, and the quilt slid beneath her. The room blurred into a watercolor of clouds and silver train tracks. When she reached the rabbit, she pressed her cheek against Mr. Pounce’s soft fur and breathed a contented sigh. It was a small victory, but it was hers.\n\nShe did not stop there. A slight tremor of a teapot on the windowsill caught her attention. Her eyes followed the sound of the liquid that trembled like a tiny drum. She pressed her tiny chest against the quilt, the rubbery texture of the toy train under her fingers, and moved again. This time, she crawled past the train, her head cocked to the side, listening to the faint rustle of a leaf outside.\n\nShe found the teapot’s gentle vibration, and then something else caught her eye. A patch of moss under a stone on the garden’s path. It was a small, green island that seemed to beckon. Lila’s heart thudded; she had never seen such a thing from her tiny, ground‑level view. She crawled towards it, her legs working in a rhythm of determination. The quilt slipped beneath her, her fingers brushing the soft fur of Mr. Pounce, who now lay on her back, a faithful shadow.\n\nWith a final push of her limbs, she reached the moss. It was cool under her fingertips, a surprise in the warm afternoon. She stared at it, and in that instant, she felt as if she had crossed a bridge between two worlds: the familiar room and the wild, waiting garden.\n\nHer mother’s hand touched her shoulder, and she whispered, “You did it, love.” The baby’s cheeks turned a rosy pink, and she giggled—a sound like a tiny bell chiming in the quiet.\n\nWhen the sun climbed higher, the light flooded the nursery, making the quilt look like a soft, golden blanket. Lila, now a tiny, triumphant explorer, found a new favorite spot by the window. She lay there, the rabbit beside her, watching the butterfly flutter across the glass. She felt a sense of wonder that would follow her into every step she would take in the days to come.\n\nThe baby had crawled. She had not only learned to move across a quilt, but she had discovered that the world was far larger than she had imagined. It was a lesson in patience, a story in tiny limbs, and a promise that every step—no matter how small—was part of a grand adventure.

### Bonus

See if you can prompt an LLM to perform sentiment analysis (output 'Positive' or 'Negative' only) on a given piece of text.

In [ ]:
# ANSWER

## Conclusion

We worked with a few Large Language Models (LLMs) using Groq and experimented with prompting for summarisation, text completion and question-answering tasks.

We also explored controlling the randomness (creativity) of output through the temperature setting and tried different types of prompting to achieve desired forms of output.

## References
1. [Groq's prompting guide](https://console.groq.com/docs/prompting)
2. [Groq's playground](https://console.groq.com/playground)



---



---



> > > > > > > > > © 2026 Institute of Data


---



---